# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)
tensor

tensor([[0.5441, 0.7165, 0.0808, 0.5901, 0.2566, 0.3125, 0.8284],
        [0.0317, 0.2908, 0.7326, 0.1340, 0.2991, 0.4947, 0.1999],
        [0.5318, 0.3563, 0.5476, 0.9208, 0.5765, 0.8846, 0.2376],
        [0.9556, 0.8912, 0.7953, 0.3649, 0.6542, 0.6783, 0.2599],
        [0.0144, 0.5462, 0.3896, 0.5912, 0.4659, 0.1037, 0.5558],
        [0.0674, 0.6835, 0.4663, 0.4560, 0.2659, 0.7032, 0.1677],
        [0.2104, 0.5624, 0.3041, 0.9194, 0.0048, 0.7125, 0.2076]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
tensor2 = torch.rand(1, 7)
# Perform matrix multiplication 
tensor2 = tensor2.reshape(7, 1)
tensor @ tensor2

tensor([[1.9696],
        [1.1316],
        [2.1540],
        [2.7937],
        [1.5558],
        [1.4723],
        [1.5747]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
C = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
D = torch.rand(1, 7)
D = D.reshape(7, 1)

# Matrix multiply tensors
C @ D

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [19]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

tensor([[0.9217, 0.6808, 0.5633, 0.4963, 0.4012],
        [0.5627, 0.3858, 0.4965, 0.5638, 0.1089],
        [0.2379, 0.9037, 0.0942, 0.4641, 0.9946],
        [0.6806, 0.5142, 0.0667, 0.7477, 0.1439],
        [0.3581, 0.3322, 0.4260, 0.5055, 0.9124]], device='cuda:0')


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [26]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
R = torch.rand(2, 3)
R = R.to(device)

torch.manual_seed(RANDOM_SEED)
G = torch.rand(2, 3)
G = G.to(device)

print(R)
print(G)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [32]:
# Perform matmul on tensor_A and tensor_B
G = G.reshape(3, 2)
Z = R @ G
Z

tensor([[0.1204, 0.3411],
        [0.0666, 0.6596]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [34]:
# Find max
print(Z.max())
# Find min
print(Z.min())

tensor(0.6596, device='cuda:0')
tensor(0.0666, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [35]:
# Find arg max
print(Z.argmax())

# Find arg min
print(Z.argmin())

tensor(3, device='cuda:0')
tensor(2, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [36]:
# Set seed
torch.manual_seed(7)

# Create random tensor
O = torch.rand(1, 1, 1, 10)

# Remove single dimensions
Y = O.squeeze()

# Print out tensors and their shapes
O.shape, Y.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))