# 00. Fundamentos de Pytorch

Fuentes:https://www.learnpytorch.io/, https://pytorch.org/tutorials/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1


True

## Introduccion a los Tensores
### Los Tensores son una forma de representar datos numericos
## Como crear un tensor:
Los Tensor son creados usando 'torch.tensor()' => https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
escalar = torch.tensor(7)
escalar

tensor(7)

In [3]:
escalar.ndim  # nos da la dimension del tensor

0

In [4]:
escalar.item() # saca los valores de la clase tensor como un int

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim #La dimension puede relacionar con el numero de []

1

In [7]:
vector.shape  # Aqui podemos ver que, en efecto tenemos elementos en un 2x1

torch.Size([2])

In [8]:
# MATRIX
MATRIX =  torch.tensor([[7, 8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape  #Ahora nos da unas dimensiones de 2x2

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],  #Las variables que sean matrices o tensores se nombran en mayusculas por convencion.
                        [4, 5, 6],
                        [1, 3, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [1, 3, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape  # Nos dice que tenemos una matriz de 3x3

torch.Size([1, 3, 3])

In [14]:
TENSOR2 = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                         [1, 3, 5]],
                        [[3, 5, 6],
                         [6, 7, 3],
                         [4, 5, 6]]])
TENSOR2

tensor([[[1, 2, 3],
         [4, 5, 6],
         [1, 3, 5]],

        [[3, 5, 6],
         [6, 7, 3],
         [4, 5, 6]]])

In [15]:
TENSOR2.ndim

3

In [16]:
TENSOR2.shape # Ahora se han creado 2 matrices es 3x3

torch.Size([2, 3, 3])

Se puede ver que un escalar es la unidad basica, un vector es un conjunto de escalares, una matriz es un conjunto de vectores y un tensor es un cojunto de cualquiera de los anteriores.

### Tensores aleatorios
Los tensores aleatorios son importantes pues la manera en la que las redes neuronales aprenden es empezando con tensores llenos de numeros aleatorios y luego modificandolos para representar mejor los datos.

`Se empieza con numeros aleatorios -> se observan los datos -> se actualizan los numeros aleatorios -> se observan los datos -> se actualizan los numeros aleatorios`

torch.rand() => https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Crear un tensor aleatorio de size (2, 3, 3) (2 matrices de 3x3)
tensor_aleatorio = torch.rand(size = (2, 3, 3))
tensor_aleatorio

tensor([[[0.3463, 0.1722, 0.7772],
         [0.5431, 0.1700, 0.3081],
         [0.0506, 0.8341, 0.7632]],

        [[0.4765, 0.9489, 0.3245],
         [0.8442, 0.4049, 0.2198],
         [0.3997, 0.4040, 0.2414]]])

In [18]:
# Crear un tensor con una forma similar a la de una imagen
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # Alto, Ancho y Numero de canales de color (en este caso R, G, B)
# Tambien se podria hacer Numero de canales de color, Alto y Ancho

In [19]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [20]:
random_image_size_tensor.ndim

3

### Ceros y Unos

In [21]:
# Crar un tensor unicamente de ceros
ceros = torch.zeros(size=(2, 3, 3))

In [22]:
ceros*tensor_aleatorio

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [23]:
unos = torch.ones(2, 3, 3)

In [24]:
unos*tensor_aleatorio

tensor([[[0.3463, 0.1722, 0.7772],
         [0.5431, 0.1700, 0.3081],
         [0.0506, 0.8341, 0.7632]],

        [[0.4765, 0.9489, 0.3245],
         [0.8442, 0.4049, 0.2198],
         [0.3997, 0.4040, 0.2414]]])

In [25]:
unos.dtype  # A no ser que se defina uno esoecifico este sera el tipo de los tensores

torch.float32

### Crear un rango de tensores y "tensors-like"
Fuente: https://pytorch.org/docs/stable/generated/torch.arange.html

In [26]:
# Usando torch.arange()   Tambien se usa torch.range(), sin enbargo este metodo sera retirado proximamente
uno_a_diez = torch.arange(start=1, end=11, step=1)
uno_a_diez

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Crear "tensors-like"
diez_ceros = torch.zeros_like(input=uno_a_diez)   #Te devuelve un tensor de ceros del mismo "shape" que el que se introduce
diez_ceros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tipos de tensores

In [28]:
# Tensor Float 32
float_32 = torch.tensor([3.0, 6.0, 9.0],
                        dtype=None,  # Por defecto el tipo sera float 32, incluso si ponemos None. Para mas info mirar la documentacion de torch.tensor.
                        #Los mas coumunes seran Float32 y Float16.  (El numero representa la presicion del numero, es decir el numero de bits usados para representar el numero)
                        device=None,  # Por defecto  sera "cpu", pero se puede modificar a "cuda" para computar mas rapidamente. podemos saber el device de un tensor con tensor.device
                        requires_grad=False)  # Por si queremos ver el gradiantes con las operaciones de este tensor
float_32

tensor([3., 6., 9.])

In [29]:
float_32.dtype

torch.float32

In [30]:
float_16 = float_32.type(torch.float16)   # o torch.half
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_32 * float_16 #Es posible multiplicar diferentes tipos de tensores

tensor([ 9., 36., 81.])

### Manipulacion de tensores
Las operaciones que se pueden realizar con tensores son las siguientes:


*   Suma
*   Resta
*   Multiplicacion (de sus elementos)
*   Division
*   Multiplicacion de matrices

Se usaran estas operaciones para encontrar patrones dentro de in dataset.


In [32]:
# La suma de un tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
# La multiplicacion de un tensor
tensor * 10

tensor([10, 20, 30])

In [34]:
# Restar tensores
tensor - 10

tensor([-9, -8, -7])

In [35]:
#Tambien se pueden utilizar las funciones de pytorch para estas operacions
torch.mul(tensor, 10)
torch.add(tensor, 10)
torch.subtract(tensor, 10)
# ...

tensor([-9, -8, -7])

### Multiplicacion de matrices

Es la operacion con tensores mas comun dentro del Deep Learning.
Ademas de torch.matmul se puede usar el operador @ para realizar la multiplicacion de matrices.
1. Las **dimensiones internas** deberan coincidir:
*  `(3, 2) @ (3, 2)` no funcionara
*  `(2, 3) @ (3, 2)` si funcionara
2. La matriz resultante tendra las dimensiones de los elementos exteriores:
*  `(2, 3) @ (3, 2)` -> `(2, 2)`
*  `(3, 2) @ (2, 3)` -> `(3, 3)`
*  `(3, 2) @ (2, 4)` -> `(3, 4)`

In [36]:
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 4))

tensor([[0.3245, 0.3888, 0.6195, 0.3787],
        [0.2898, 0.2997, 0.4906, 0.3221],
        [0.7772, 0.7660, 1.2658, 0.8510]])

In [38]:
A_tensor = torch.tensor([[1, 2],
                         [3, 4],
                         [5,6]])

B_tensor = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


Si queremos multiplicar A con B, tendremos que manipular el "shape" de una de las matrices usando **transpose**.
Un **transpose** modifica los ejes o las dimensiones de un tensor dado:

In [39]:
B_tensor

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [40]:
B_tensor.T  # Hace la transpuesta de la matriz
# De esta manera la multiplicacion funcionara sin problemas

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [41]:
torch.mm(A_tensor, B_tensor.T)    # mm funciona igual que matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Como encontrar min, max, mean, sum, ... (tensor aggregation)

In [42]:
x = torch.arange(0, 100, 10)

In [43]:
# Emncontrar el minimo
torch.min(x), x.min()

(tensor(0), tensor(0))

In [44]:
# Encontrar el maximo
torch.max(x), x.max()

(tensor(90), tensor(90))

In [45]:
# Encontrar la media
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # Requiere datos de tipo Float o Complex

(tensor(45.), tensor(45.))

In [46]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [47]:
index = 0
for element in x:
  if element == x.max():
    print(element)
    print(index)
  index +=1

  # Esta seria la forma manual de encontrar el maximo dentro de un tensor.

tensor(90)
9


In [48]:
x.argmax(), x.argmin()  # Esto seria utilizando los metodos de pytorch. (mucho mas eficiente)

(tensor(9), tensor(0))

### "Reshaping", "stracking", "squeezing" and "unsqueezing" tensores
*  "Reshaping" -> Remodela un tesor de una figura definida.
*  "View" -> Devuelve una vista de un tensor de una cierta figura se comparte la misma memoria.
*  "Stacking" -> Convina multiples tensores uno encima de otro (vstack) o uno al lado del otro (hstack). (https://pytorch.org/docs/stable/generated/torch.stack.html), (https://pytorch.org/docs/stable/generated/torch.hstack.html), (https://pytorch.org/docs/stable/generated/torch.vstack.html)
*  "Squeeze" -> Elimina todas las "single dimensions" de un tensor.
*  "Unsqueeze" -> Añade una "single dimension" a un tensor.
*  "Permute" -> Devuelve una vista del input con las dimensiones permitadas de cierta manera.

In [49]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [50]:
x_reshaped = x.reshape(1, 10)  # La multiplicacion de los argumentos del reshape ha de ser igual el size del tensor
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [51]:
z = x.view(5, 2)    # Como comparten la misma memoria, modificando uno se modificara el otro
z, z.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [52]:
# "Stack" tensores
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [53]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_reshaped  #Se elimina la parte del tensor que tienen dimension 1

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]))

In [54]:
# Se las dimensiones son size(dim 0, dim 1, dim 2, ...)
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)  #Se añade una "single dimension" donde le digamos
x_unsqueezed, x_unsqueezed.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [55]:
# torch.permute => reordena las dimensiones de un tensor de una manera determinada  (https://pytorch.org/docs/stable/generated/torch.permute.html)
x_original = torch.rand(size = (224, 224, 3)) # (alto, ancho y canales de color)
x_permuted = x_original.permute(2, 0, 1)  # Se permuta el orden del tensor de la siguiente manera (canales de color, alto y ancho)
x_original.shape, x_permuted.shape  # Como se comporta la funcion permute ambos compartiran el mismo espacio de memoria. Es decir si se modifican los valores en una, la modificacion hara efecto en ambas

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### Indexing (seleccionar datos de tensores)

In [56]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [57]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
x[0, 0] # [dim 0, dim 1, dim 2, ...]

tensor([1, 2, 3])

In [59]:
x[0, 0, 0]

tensor(1)

In [60]:
# Se puede utilizar : para acceder a esa dimension por completo
x[:, :, 1]

tensor([[2, 5, 8]])

In [61]:
x[:, 1, 1]

tensor([5])

In [62]:
x[0, 0, :]

tensor([1, 2, 3])

In [63]:
x[0, 2, 2]

tensor(9)

In [64]:
x[:, :, 2]

tensor([[3, 6, 9]])

### Tensores de Pytorch y Numpy

Numpy es una libreria popular para la computacion numerica en python.

Es por esto que Pytorch tienen una funcionalidad para interacutar con ella.

*  Se pueden cambiar los datos en Numpy para que se vuelvan un tensor de PyTorch -> `torch.from_numpy(ndarray)`
*  Tambien se pueden cambiar los tensores de PyTorch a datos de Numpy -> `torch.Tensor.numpy()`

(Ninguno de estos metodos comparten memoria)

In [65]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [66]:
array.dtype, tensor.dtype   # El tipo de datos por defecto de np es float64

(dtype('float64'), torch.float64)

In [67]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibilidad
Para reducir la aleatoriedad en redes neuronales se utiliza el concepto de **random seed**.

https://pytorch.org/docs/stable/notes/randomness.html

In [68]:
A_tensor = torch.rand(3, 4)
B_tensor = torch.rand(3, 4)

print(A_tensor == B_tensor)   # Nos dira si alguno de los valores son iguales

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [69]:
RANDOM_SEED = 12

torch.manual_seed(RANDOM_SEED)
C_random =  torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)  # Esto se deberia de hacer cada vez que se cree un tensor aleatorio
D_random = torch.rand(3, 4)

print(C_random)
print(D_random)
print(C_random == D_random)

tensor([[0.4657, 0.2328, 0.4527, 0.5871],
        [0.4086, 0.1272, 0.6373, 0.2421],
        [0.7312, 0.7224, 0.1992, 0.6948]])
tensor([[0.4657, 0.2328, 0.4527, 0.5871],
        [0.4086, 0.1272, 0.6373, 0.2421],
        [0.7312, 0.7224, 0.1992, 0.6948]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Ejecutar tensores y objetos de PyTorch en una GPU para relaciar las operaciones mas rapidamente

In [70]:
torch.cuda.is_available()   # Para comprobar si PyTorch acceso a la GPU

True

In [71]:
!nvidia-smi

Sat Jul 22 02:04:19 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.40                 Driver Version: 536.40       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti   WDDM  | 00000000:01:00.0  On |                  N/A |
| 28%   34C    P8              26W / 260W |   1569MiB / 11264MiB |      6%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [72]:
device = "cuda" if torch.cuda.is_available() else "cpu"    # Para inicializar el codigo en la GPU
device

'cuda'

In [73]:
torch.cuda.device_count()   # Para contar el numero de GPUs disponibles (Si se tiene mas de una)

1

### Como poner tensores (y modelos) en la gpu.
https://pytorch.org/docs/stable/cuda.html

In [74]:
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [75]:
# Para mover los tensores a la gpu
gpu_tensor = tensor.to(device)
gpu_tensor

tensor([1, 2, 3], device='cuda:0')

### Como devolverlos a la cpu (para hacer calculos con Numpy)

In [76]:
cpu_tensor = gpu_tensor.cpu()
cpu_tensor, cpu_tensor.device

(tensor([1, 2, 3]), device(type='cpu'))